apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: booking-auth-ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-url: http://auth-server.default.svc.cluster.local:3000/auth/verify
    nginx.ingress.kubernetes.io/enable-opentelemetry: "true"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /auth/verify
        pathType: Prefix
        backend:
          service:
            name: auth-server
            port:
              number: 3000

